import re
import json
import codecs
import os

# Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
HTML_OUTPUT_PATH = os.path.join(BASE_DIR, 'index.html')
JS_OUTPUT_PATH = os.path.join(BASE_DIR, 'chapters.js')
ASSETS_DIR = os.path.join(BASE_DIR, 'Assets')

# Find extracted_text.txt in multiple possible locations
TEXT_PATH_LOCAL = os.path.join(BASE_DIR, 'extracted_text.txt')
TEXT_PATH_OTHER = os.path.join(os.path.dirname(BASE_DIR), 'Other tasks', 'extracted_text.txt')

if os.path.exists(TEXT_PATH_LOCAL):
    TEXT_PATH = TEXT_PATH_LOCAL
elif os.path.exists(TEXT_PATH_OTHER):
    TEXT_PATH = TEXT_PATH_OTHER
else:
    TEXT_PATH = TEXT_PATH_LOCAL

def parse_txt_to_json(file_path):
    if not os.path.exists(file_path):
        print(f"Error: Text file not found at {file_path}")
        return [], []
        
    print(f"Reading text from: {file_path}")
    with open(file_path, 'r', encoding='utf-8') as f:
        text = f.read()

    lines = text.split('\n')
    
    chapters = []
    current_chapter = None
    intro_paragraphs = []
    
    for line in lines:
        line_stripped = line.strip()
        if not line_stripped:
            continue
        
        # Detect Chapter Header (e.g., "Chương 1: Nemarian" or "Chương 1 : Nemarian")
        match = re.match(r'^Chương\s+(\d+)\s*:\s*(.*)', line_stripped, re.IGNORECASE)
        if match:
            if current_chapter:
                chapters.append(current_chapter)
            
            ch_num = int(match.group(1))
            ch_title = match.group(2).strip()
            current_chapter = {
                "id": ch_num,
                "title": f"Chương {ch_num}: {ch_title}",
                "paragraphs": []
            }
        else:
            if current_chapter:
                current_chapter["paragraphs"].append(line_stripped)
            else:
                intro_paragraphs.append(line_stripped)
                
    if current_chapter:
        chapters.append(current_chapter)
        
    return intro_paragraphs, chapters

def main():
    print("Parsing text file...")
    intro, chapters = parse_txt_to_json(TEXT_PATH)
    
    if not chapters:
        print("Parsing failed: No chapters found. Please check extracted_text.txt path.")
        return
        
    print(f"Parsed {len(chapters)} chapters and {len(intro)} intro paragraphs.")
    
    # Serialize to JSON strings
    intro_json = json.dumps(intro, ensure_ascii=False, indent=2)
    chapters_json = json.dumps(chapters, ensure_ascii=False, indent=2)
    
    # Compile chapters.js
    js_content = f"""// Generated automatically by build_novel.py. Do not edit this file manually.
window.INTRO_TEXT = {intro_json};
window.CHAPTERS_DATA = {chapters_json};
"""
    
    print(f"Writing parsed novel data to {JS_OUTPUT_PATH}...")
    with codecs.open(JS_OUTPUT_PATH, 'w', encoding='utf-8-sig') as f:
        f.write(js_content)
        
    # Check chapters.js size
    js_size_mb = os.path.getsize(JS_OUTPUT_PATH) / 1024 / 1024
    print(f"Build successful! chapters.js size: {js_size_mb:.2f} MB")
    print(f"You can now open index.html locally or deploy the directory.")

if __name__ == '__main__':
    main()
